/* !!! Do not manually modify this file in the production stage !!!
 * This file is automatically created by MakeResBin.exe,
 * and used in the production stage.*/

#define         RES_DOT_MATRIX          	0
#define         RES_FONT                	1
#define         RES_JPEG_TAB            	2
#define         RES_MINIDV              	3
#define         RES_OSD_SOURCE          	4
#define         RES_PALETTE_TAB         	5
#define         RES_PHOTO_SOUND         	6
#define         RES_POWER_OFF           	7
#define         RES_POWER_OFF_MUSIC     	8
#define         RES_POWER_ON            	9
#define         RES_POWER_ON_MUSIC      	10
#define         RES_USB_DEV_ICON        	11
